import { CheeseBreadItem, Bakery, Achievement, Language, UsageMetric } from "./types";

export const MENU_ITEMS: CheeseBreadItem[] = [
  {
    id: "classic",
    name: {
      pt: "Pão de Queijo Tradicional",
      en: "Traditional Cheese Bread",
      es: "Pan de Queso Tradicional",
    },
    description: {
      pt: "Receita tradicional mineira com queijo Canastra meia cura curado artesanalmente. Casquinha crocante e miolo super macio.",
      en: "Traditional recipe with artisanal semi-cured Canastra cheese. Crispy golden crust with a soft, pillowy inside.",
      es: "Receta tradicional de Minas con queso Canastra semicurado artesanal. Corteza crujiente e interior súper suave.",
    },
    price: 4.5,
    points: 10,
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&q=80&w=600",
    category: "classic",
    rating: 4.9,
  },
  {
    id: "catupiry",
    name: {
      pt: "Recheado com Requeijão",
      en: "Cream Cheese Stuffed",
      es: "Relleno de Queso Crema",
    },
    description: {
      pt: "O tradicional pão de queijo com um recheio generoso e cremoso de requeijão culinário mineiro original.",
      en: "Our traditional cheese bread stuffed with a rich and creamy original Brazilian cream cheese filling.",
      es: "El tradicional pan de queso con un relleno generoso y cremoso de requesón culinario original de Minas.",
    },
    price: 6.0,
    points: 15,
    image: "https://images.unsplash.com/photo-1608039755401-742074f0548d?auto=format&fit=crop&q=80&w=600",
    category: "filled",
    rating: 4.8,
  },
  {
    id: "sausage",
    name: {
      pt: "Especial com Linguiça",
      en: "Smoked Sausage Special",
      es: "Especial con Chorizo",
    },
    description: {
      pt: "Combinação dos deuses: massa de pão de queijo com pedaços de linguiça suína defumada artesanal e um toque de ervas.",
      en: "Heavenly match: cheese bread dough mixed with premium smoked pork sausage chunks and a hint of herbs.",
      es: "Combinación celestial: masa de pan de queso con trozos de chorizo ahumado artesanal y un toque de hierbas.",
    },
    price: 7.5,
    points: 20,
    image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&q=80&w=600",
    category: "special",
    rating: 4.95,
  },
  {
    id: "dulce",
    name: {
      pt: "Recheado de Doce de Leite",
      en: "Stuffed with Dulce de Leche",
      es: "Relleno de Dulce de Leche",
    },
    description: {
      pt: "Contraste delicioso entre a massa salgadinha de queijo e o recheio cremoso do legítimo doce de leite de Viçosa.",
      en: "Delicious contrast between the savory cheese dough and a creamy filling of legitimate Viçosa milk caramel.",
      es: "Delicioso contraste entre la masa salada de queso y el relleno cremoso del legítimo dulce de leche de Viçosa.",
    },
    price: 6.5,
    points: 15,
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=600",
    category: "filled",
    rating: 4.7,
  },
  {
    id: "multigrain",
    name: {
      pt: "Multigrãos Fit",
      en: "Multigrain Fit",
      es: "Multicereales Fit",
    },
    description: {
      pt: "Versão nutritiva feita com queijo minas frescal light, farinha de linhaça, chia, gergelim e sementes de girassol.",
      en: "Nutritious version made with light Minas fresh cheese, flaxseed, chia, sesame, and sunflower seeds.",
      es: "Versión nutritiva elaborada con queso fresco ligero, linaza, chía, sésamo y semillas de girasol.",
    },
    price: 5.5,
    points: 12,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600",
    category: "classic",
    rating: 4.6,
  },
  {
    id: "vegan",
    name: {
      pt: "Vegano de Mandioca",
      en: "Vegan Cassava Pão",
      es: "Vegano de Mandioca",
    },
    description: {
      pt: "Delicioso pãozinho livre de crueldade à base de polvilho, batata baroa, mandioca orgânica, óleo de coco e levedura nutricional.",
      en: "Delicious dairy-free and gluten-free snack made of tapioca starch, cassava, coconut oil, and nutritional yeast.",
      es: "Delicioso bocadillo vegano elaborado a base de mandioca orgánica, fécula de tapioca, aceite de coco y levadura nutricional.",
    },
    price: 5.5,
    points: 12,
    image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&q=80&w=600",
    category: "special",
    rating: 4.75,
  }
];

export const MOCK_BAKERIES: Bakery[] = [
  {
    id: "ouro",
    name: "Forno D'Ouro - Savassi",
    address: "Rua Antônio de Albuquerque, 620 - Savassi, Belo Horizonte - MG",
    distance: 0.4,
    rating: 4.9,
    reviewsCount: 142,
    hours: "07:00 - 20:00",
    phone: "(31) 3225-8890",
    lat: -19.9382,
    lng: -43.9355,
    reviews: [
      {
        id: "r1",
        userName: "Mariana Silva",
        rating: 5,
        comment: "O pão de queijo tradicional sempre sai quentinho às 08:00 e às 16:00. O melhor queijo Canastra da Savassi!",
        date: "2026-06-28",
        cheeseBreadType: "Pão de Queijo Tradicional",
        userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100"
      },
      {
        id: "r2",
        userName: "Carlos Henrique",
        rating: 4,
        comment: "Excelente atendimento e pão de queijo recheado maravilhoso. O café expresso acompanha muito bem.",
        date: "2026-06-25",
        cheeseBreadType: "Recheado com Requeijão",
        userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100"
      }
    ]
  },
  {
    id: "canastra",
    name: "Casarão do Canastra - Lourdes",
    address: "Av. Álvares Cabral, 1120 - Lourdes, Belo Horizonte - MG",
    distance: 1.2,
    rating: 4.8,
    reviewsCount: 98,
    hours: "07:30 - 19:30",
    phone: "(31) 3245-1212",
    lat: -19.9285,
    lng: -43.9412,
    reviews: [
      {
        id: "r3",
        userName: "Fernanda Costa",
        rating: 5,
        comment: "A linguiça artesanal que eles misturam na massa é simplesmente sensacional. Vale cada centavo!",
        date: "2026-06-30",
        cheeseBreadType: "Especial com Linguiça",
        userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=100"
      },
      {
        id: "r4",
        userName: "Thiago Ramos",
        rating: 5,
        comment: "Lugar super aconchegante, o agendamento pelo app funciona perfeitamente. Cheguei e meu pedido já estava embalado quente!",
        date: "2026-06-22",
        cheeseBreadType: "Pão de Queijo Tradicional",
        userAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100"
      }
    ]
  },
  {
    id: "central",
    name: "Estação do Pão de Queijo - Centro",
    address: "Rua dos Tupis, 250 - Centro, Belo Horizonte - MG",
    distance: 2.5,
    rating: 4.7,
    reviewsCount: 210,
    hours: "06:00 - 21:00",
    phone: "(31) 3201-4478",
    lat: -19.9192,
    lng: -43.9388,
    reviews: [
      {
        id: "r5",
        userName: "Aline Oliveira",
        rating: 4,
        comment: "Muito rápido, ideal para quem está com pressa no Centro. O pão de queijo com doce de leite é o meu pecado de todas as tardes.",
        date: "2026-07-01",
        cheeseBreadType: "Recheado de Doce de Leite",
        userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=100"
      },
      {
        id: "r6",
        userName: "Pedro Alencar",
        rating: 5,
        comment: "Opção vegana de mandioca maravilhosa! Textura excelente que não deixa nada a desejar ao tradicional.",
        date: "2026-06-15",
        cheeseBreadType: "Vegano de Mandioca",
        userAvatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=100"
      }
    ]
  },
  {
    id: "pampulha",
    name: "Forno de Minas Gourmet - Pampulha",
    address: "Av. Otacílio Negrão de Lima, 3200 - Pampulha, Belo Horizonte - MG",
    distance: 6.8,
    rating: 4.95,
    reviewsCount: 320,
    hours: "08:00 - 20:00",
    phone: "(31) 3491-9900",
    lat: -19.8584,
    lng: -43.9785,
    reviews: [
      {
        id: "r7",
        userName: "Juliana Mendes",
        rating: 5,
        comment: "Comer pão de queijo quente olhando para a Lagoa da Pampulha é a melhor experiência de BH. App agiliza demais!",
        date: "2026-07-02",
        cheeseBreadType: "Pão de Queijo Tradicional",
        userAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=100"
      }
    ]
  }
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: "first_bite",
    title: {
      pt: "Primeira Fornada",
      en: "First Batch",
      es: "Primera Hornada",
    },
    description: {
      pt: "Realizou seu primeiro agendamento pelo aplicativo.",
      en: "Placed your first order schedule through the app.",
      es: "Realizó su primer pedido programado a través de la app.",
    },
    pointsAwarded: 50,
    unlocked: true,
    unlockedAt: "2026-07-01T10:00:00Z",
    icon: "🔥"
  },
  {
    id: "cheese_lover",
    title: {
      pt: "Mestre Queijeiro",
      en: "Cheese Master",
      es: "Maestro Quesero",
    },
    description: {
      pt: "Acumule mais de 150 pontos no sistema de fidelidade.",
      en: "Collect over 150 points in the loyalty program.",
      es: "Acumule más de 150 puntos en el programa de fidelidad.",
    },
    pointsAwarded: 100,
    unlocked: false,
    icon: "👑"
  },
  {
    id: "explorer",
    title: {
      pt: "Explorador de Minas",
      en: "Mineiro Explorer",
      es: "Explorador de Minas",
    },
    description: {
      pt: "Agendou pão de queijo em 3 padarias diferentes.",
      en: "Ordered cheese bread from 3 different bakery locations.",
      es: "Pidió pan de queso en 3 panaderías diferentes.",
    },
    pointsAwarded: 150,
    unlocked: false,
    icon: "📍"
  },
  {
    id: "morning_person",
    title: {
      pt: "Madrugador do Pãozinho",
      en: "Early Pãozinho Riser",
      es: "Madrugador del Pancito",
    },
    description: {
      pt: "Agendou uma busca para antes das 08:00 da manhã.",
      en: "Scheduled a pickup for before 08:00 AM.",
      es: "Programó una recogida para antes de las 08:00 AM.",
    },
    pointsAwarded: 80,
    unlocked: false,
    icon: "☀️"
  }
];

export const MOCK_METRICS: UsageMetric[] = [
  { month: "Jan", pointsEarned: 80, breadsEaten: 8, co2Saved: 1.2, amountSpent: 36.0 },
  { month: "Feb", pointsEarned: 110, breadsEaten: 11, co2Saved: 1.6, amountSpent: 49.5 },
  { month: "Mar", pointsEarned: 150, breadsEaten: 14, co2Saved: 2.1, amountSpent: 63.0 },
  { month: "Apr", pointsEarned: 120, breadsEaten: 12, co2Saved: 1.8, amountSpent: 54.0 },
  { month: "May", pointsEarned: 190, breadsEaten: 18, co2Saved: 2.7, amountSpent: 85.5 },
  { month: "Jun", pointsEarned: 240, breadsEaten: 22, co2Saved: 3.3, amountSpent: 104.5 }
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  pt: {
    appName: "App de Pão de Queijo",
    tagline: "Pão de queijo quentinho sempre no seu horário",
    tabOrder: "Pedir",
    tabBakeries: "Padarias",
    tabLoyalty: "Fidelidade",
    tabChat: "Suporte",
    tabDashboard: "Painel",
    biometricsTitle: "Autenticação Biométrica",
    biometricsUnlock: "Toque para autenticar por Biometria (FaceID/Digital)",
    biometricsSuccess: "Autenticado com sucesso por biometria!",
    biometricsLoading: "Lendo dados biométricos...",
    biometricsStatus: "Autenticação requerida para transações seguras",
    statusOnline: "Online",
    statusOffline: "Modo Offline (Consulta Básica)",
    offlineNotice: "Você está navegando em modo offline. Consultas e pedidos usam o cache local.",
    scheduleTitle: "Agende sua Encomenda",
    selectBakery: "Selecione a Padaria",
    selectItems: "Selecione os Pães de Queijo",
    scheduleTime: "Horário de Busca",
    choosePayment: "Forma de Pagamento",
    confirmOrder: "Agendar Encomenda",
    emptyCart: "Seu carrinho está vazio",
    addCart: "Adicionar ao Carrinho",
    viewCart: "Ver Carrinho",
    paymentPending: "Aguardando pagamento",
    paymentPaid: "Pago",
    statusPending: "Confirmando",
    statusPreparing: "No Forno",
    statusReady: "Quentinho! (Pronto para Buscar)",
    statusPickedUp: "Entregue",
    pointsLabel: "Pontos",
    levelLabel: "Nível",
    loyaltySection: "Seu Programa de Fidelidade",
    loyaltyBenefits: "A cada pão de queijo comprado, ganhe pontos para trocar por brindes!",
    achievementsTitle: "Suas Conquistas",
    socialShare: "Compartilhar Conquistas",
    shareSuccess: "Sucesso compartilhado nas redes sociais!",
    shareCaption: "Olha só a minha conquista no App de Pão de Queijo: ",
    chatPlaceholder: "Pergunte ao Pãozinho (IA)...",
    chatGreeting: "Olá! Sou o Pãozinho, o assistente virtual da padaria. Tem alguma dúvida sobre pães de queijo, encomendas, fidelidade ou onde buscar?",
    metricTitle: "Suas Métricas de Consumo",
    metricPoints: "Pontos Acumulados",
    metricBreads: "Pães de Queijo Consumidos",
    metricCo2: "CO2 Economizado",
    metricCo2Desc: "Ao buscar na padaria a pé ao invés de usar carros de entrega",
    metricSpend: "Gasto Mensal",
    recentOrders: "Encomendas Recentes",
    addReview: "Adicionar Avaliação",
    writeReview: "Escreva sua opinião...",
    reviewPlaceholder: "O que você achou dos nossos pães de queijo e serviço?",
    reviewSuccess: "Obrigado por sua avaliação!",
    filterCategory: "Categoria",
    classic: "Clássicos",
    special: "Especiais",
    filled: "Recheados",
    priceRange: "Preço",
    distanceFilter: "Distância Máxima",
    nearbyBakeries: "Padarias Próximas",
    routeDirections: "Traçar Rota",
    callBakery: "Ligar",
    activeOrders: "Pedidos Ativos",
    orderCode: "Código de Busca",
    orderTotal: "Total do Pedido",
    backMenu: "Voltar ao Menu",
    checkoutTitle: "Finalizar e Pagar",
    pixInstructions: "Escaneie o QR Code ou copie o código Pix para pagar.",
    cardInstructions: "Insira os dados do seu cartão de crédito simulado.",
    applePayInstructions: "Toque no botão abaixo para pagar com Apple Pay simulado.",
    paySuccess: "Pagamento Aprovado!",
    simulateNotify: "Notificação inteligente enviada!",
    smartPushMsg: "Pãozinho diz: Seu pão de queijo favorito está saindo quentinho no forno da Savassi agora! Agende já! 🧀"
  },
  en: {
    appName: "Cheese Bread App",
    tagline: "Warm cheese bread, scheduled perfectly for you",
    tabOrder: "Order",
    tabBakeries: "Bakeries",
    tabLoyalty: "Loyalty",
    tabChat: "Support",
    tabDashboard: "Dashboard",
    biometricsTitle: "Biometric Authentication",
    biometricsUnlock: "Tap to authenticate with Biometrics (FaceID/Fingerprint)",
    biometricsSuccess: "Successfully authenticated with biometrics!",
    biometricsLoading: "Reading biometric data...",
    biometricsStatus: "Authentication required for secure checkouts",
    statusOnline: "Online",
    statusOffline: "Offline Mode (Basic Cache)",
    offlineNotice: "You are browsing offline. Viewings and orders use local cached data.",
    scheduleTitle: "Schedule Your Order",
    selectBakery: "Select Bakery",
    selectItems: "Select Cheese Breads",
    scheduleTime: "Pickup Time",
    choosePayment: "Payment Method",
    confirmOrder: "Schedule Order",
    emptyCart: "Your cart is empty",
    addCart: "Add to Cart",
    viewCart: "View Cart",
    paymentPending: "Waiting payment",
    paymentPaid: "Paid",
    statusPending: "Confirming",
    statusPreparing: "In the Oven",
    statusReady: "Warm & Ready! (Ready for Pickup)",
    statusPickedUp: "Delivered",
    pointsLabel: "Points",
    levelLabel: "Level",
    loyaltySection: "Your Loyalty Program",
    loyaltyBenefits: "Every cheese bread you buy earns points towards free batches!",
    achievementsTitle: "Your Achievements",
    socialShare: "Share Achievement",
    shareSuccess: "Achievement shared on social media!",
    shareCaption: "Check out my achievement on the Cheese Bread App: ",
    chatPlaceholder: "Ask Pãozinho (AI)...",
    chatGreeting: "Hello! I'm Pãozinho, your virtual bakery assistant. Got any questions about cheese bread, orders, rewards, or pickup locations?",
    metricTitle: "Your Consumption Metrics",
    metricPoints: "Points Accumulated",
    metricBreads: "Cheese Breads Eaten",
    metricCo2: "CO2 Saved",
    metricCo2Desc: "By picking up on foot instead of using motor vehicle deliveries",
    metricSpend: "Monthly Spending",
    recentOrders: "Recent Orders",
    addReview: "Add Review",
    writeReview: "Write your review...",
    reviewPlaceholder: "What did you think of our cheese breads and service?",
    reviewSuccess: "Thank you for your review!",
    filterCategory: "Category",
    classic: "Classics",
    special: "Specials",
    filled: "Stuffed",
    priceRange: "Price",
    distanceFilter: "Max Distance",
    nearbyBakeries: "Nearby Bakeries",
    routeDirections: "Get Directions",
    callBakery: "Call",
    activeOrders: "Active Orders",
    orderCode: "Pickup Code",
    orderTotal: "Order Total",
    backMenu: "Back to Menu",
    checkoutTitle: "Checkout & Pay",
    pixInstructions: "Scan the QR Code or copy the Pix code to pay.",
    cardInstructions: "Enter your simulated credit card details.",
    applePayInstructions: "Tap the button below to pay with simulated Apple Pay.",
    paySuccess: "Payment Approved!",
    simulateNotify: "Smart notification triggered!",
    smartPushMsg: "Pãozinho says: Your favorite cheese bread is coming fresh out of the oven at Savassi right now! Book yours! 🧀"
  },
  es: {
    appName: "App de Pan de Queso",
    tagline: "Pan de queso calientito, programado para ti",
    tabOrder: "Pedir",
    tabBakeries: "Panaderías",
    tabLoyalty: "Fidelidad",
    tabChat: "Soporte",
    tabDashboard: "Panel",
    biometricsTitle: "Autenticación Biométrica",
    biometricsUnlock: "Toque para autenticar por biometría (FaceID/Huella)",
    biometricsSuccess: "¡Autenticado con éxito por biometría!",
    biometricsLoading: "Leyendo datos biométricos...",
    biometricsStatus: "Autenticación requerida para transacciones seguras",
    statusOnline: "En línea",
    statusOffline: "Modo Offline (Consulta Básica)",
    offlineNotice: "Estás navegando sin conexión. Las consultas y pedidos usan caché local.",
    scheduleTitle: "Programe su Pedido",
    selectBakery: "Seleccione Panadería",
    selectItems: "Seleccione Panes de Queso",
    scheduleTime: "Hora de Recogida",
    choosePayment: "Método de Pago",
    confirmOrder: "Programar Pedido",
    emptyCart: "Tu carrito está vacío",
    addCart: "Añadir al Carrito",
    viewCart: "Ver Carrito",
    paymentPending: "Pago pendiente",
    paymentPaid: "Pagado",
    statusPending: "Confirmando",
    statusPreparing: "En el Horno",
    statusReady: "¡Calientito! (Listo para Recoger)",
    statusPickedUp: "Entregado",
    pointsLabel: "Puntos",
    levelLabel: "Nivel",
    loyaltySection: "Tu Programa de Fidelidad",
    loyaltyBenefits: "Cada pan de queso comprado suma puntos para canjear por productos gratis.",
    achievementsTitle: "Tus Logros",
    socialShare: "Compartir Logros",
    shareSuccess: "¡Logro compartido en redes sociales!",
    shareCaption: "Mira mi logro en la App de Pan de Queso: ",
    chatPlaceholder: "Pregunta a Pãozinho (IA)...",
    chatGreeting: "¡Hola! Soy Pãozinho, tu asistente de panadería virtual. ¿Tienes dudas sobre panes de queso, pedidos, fidelidad o dónde recoger?",
    metricTitle: "Tus Métricas de Consumo",
    metricPoints: "Puntos Acumulados",
    metricBreads: "Panes de Queso Consumidos",
    metricCo2: "CO2 Ahorrado",
    metricCo2Desc: "Al recoger a pie en lugar de usar autos de entrega",
    metricSpend: "Gasto Mensual",
    recentOrders: "Pedidos Recientes",
    addReview: "Añadir Reseña",
    writeReview: "Escribe tu opinión...",
    reviewPlaceholder: "¿Qué te parecieron nuestros panes de queso y el servicio?",
    reviewSuccess: "¡Gracias por tu reseña!",
    filterCategory: "Categoría",
    classic: "Clásicos",
    special: "Especiales",
    filled: "Rellenos",
    priceRange: "Precio",
    distanceFilter: "Distancia Máxima",
    nearbyBakeries: "Panaderías Cercanas",
    routeDirections: "Trazar Ruta",
    callBakery: "Llamar",
    activeOrders: "Pedidos Activos",
    orderCode: "Código de Entrega",
    orderTotal: "Total del Pedido",
    backMenu: "Volver al Menú",
    checkoutTitle: "Finalizar y Pagar",
    pixInstructions: "Escanee el código QR o copie el código Pix para pagar.",
    cardInstructions: "Ingrese los datos de su tarjeta de crédito simulada.",
    applePayInstructions: "Toque el botón abajo para pagar con Apple Pay simulado.",
    paySuccess: "¡Pago Aprobado!",
    simulateNotify: "¡Notificación inteligente activada!",
    smartPushMsg: "Pãozinho dice: ¡Tu pan de queso favorito está saliendo calientito del horno en Savassi ahora mismo! ¡Reserva ya! 🧀"
  }
};
